#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/saindex
#
# IDENTIFICATION
#    src/backend/access/saindex/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/saindex
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	sabuild.o \
	sahandler.o \
	saoperators.o \
	sasearch.o \
	sautils.o

include $(top_srcdir)/src/backend/common.mk
